title:              GCH Blog
email:              gchaixx@163.com
description:        A Blog by GCH
author:             GCH
# baseurl:            "/"
# url:                "https://Xuezha-Guo.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    Xuezha-Guo
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:




# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https\://github.com/jneen/rouge#full-options
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1